version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: crits_and_coffee_local_django
    depends_on:
      - postgres
      - mailhog
    links:
    - selenium
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  angular:
    build:
      context: .
      dockerfile: ./compose/production/angular/Dockerfile
    volumes:
      - ./clientapp/frontend-angular-app:/usr/app/
    ports:
      - 4200:4200
      - 49153:49153
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: crits_and_coffee_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  selenium:
    build:
      context: .
      dockerfile: ./compose/local/selenium/Dockerfile
    image: todays_training_docker_selenium
    ports:
      - 4444:4444   # Selenium
      - 5901:5900   # VNC server

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: crits_and_coffee_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: crits_and_coffee_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: crits_and_coffee_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
