# Generated by Django 2.0.7 on 2019-03-10 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='None', max_length=255)),
                ('id_code', models.CharField(default='None', max_length=255)),
                ('tags', models.TextField(default='None', max_length=255)),
                ('link', models.CharField(default='None', max_length=255)),
                ('image_url', models.CharField(default='None', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_time', models.DateField(blank=True)),
                ('loc_name', models.TextField(default='None', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('loc_point', django.contrib.gis.db.models.fields.PointField(default='SRID=4326;POINT(43.065019 -87.878286)', srid=4326)),
            ],
        ),
    ]
