FROM  intelpython/intelpython3_full:latest

RUN adduser -D quant

WORKDIR /quant_api

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY API_Quant app
COPY app.py config.py ./
COPY Docker_scripts/start.prod /start
RUN chmod +x /start

COPY ./Docker_scripts/entrypoint /entrypoint
RUN sed -i 's/\r//' /entrypoint
RUN chmod +x /entrypoint


ENV FLASK_APP app.py

RUN chown -R app:app ./
USER quant

EXPOSE 5000
ENTRYPOINT ["/entrypoint"]