version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    image: ${DOCKER_REGISTRY}crits_and_coffee_django:${DOCKER_TEST_TAG}
    container_name: django-test
    build:
      context: ../..
      dockerfile: testing/django/Dockerfile
    volumes:
      - ../../functional_tests:/functional_tests
    depends_on:
      - postgres
      - mailhog
    links:
      - selenium-hub
    env_file:
      - ../.envs/.private/.instagram
      - ../.envs/.testing/.django
      - ../.envs/.testing/.postgres
    ports:
      - 8000:8000
    command: /start
    networks:
      - selenuim_env

  postgres:
    image: ${DOCKER_REGISTRY}crits_and_coffee_postgres:${DOCKER_TEST_TAG}
    container_name: postgres-test
    build:
      context: ../..
      dockerfile: testing/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ../.envs/.testing/.postgres
    networks:
      - selenuim_env

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    networks:
      - selenuim_env

  redis:
    image: redis:3.2
    networks:
      - selenuim_env

  celeryworker:
    <<: *django
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_WORKER_TEST_TAG}
    container_name: ${CELERY_WORKER_TEST_TAG}
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker
    networks:
      - selenuim_env

  celerybeat:
    <<: *django
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_BEAT_TEST_TAG}
    container_name: ${CELERY_BEAT_TEST_TAG}
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
    networks:
      - selenuim_env

  flower:
    <<: *django
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${FLOWER_TEST_TAG}
    container_name: ${FLOWER_TEST_TAG}
    ports:
      - "5555:5555"
    command: /start-flower
    networks:
      - selenuim_env

  selenium-hub:
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${SELENIUM_TEST_TAG}
    container_name: selenium-test
    build:
      context: ../..
      dockerfile: testing/selenium/Dockerfile
    privileged: true
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=240000
      - GRID_BROWSER_TIMEOUT=240000
    command: /run_tests
    networks:
      - selenuim_env

  nodechrome2:
    image: selenium/node-chrome-debug
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - 5900:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenuim_env

  nodefirefox2:
    image: selenium/node-firefox-debug
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - 5901:5901
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenuim_env

networks:
    selenuim_env:

