version: '3'

volumes:
  production_caddy: {}
  production_logs: {}
services:
  caddy:
    image: ${DOCKER_REGISTRY}crits_and_coffee_caddy:${DOCKER_PRODUCTION_TAG}
    depends_on:
      - front-end-app
      - instagram-api
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ../.envs/.production/.caddy
      - ../.envs/.private/.production/.aws
    networks:
      - back-end
      - front-end
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  front-end-app:
    image: ${DOCKER_REGISTRY}crits_and_coffee_client_app:${DOCKER_PRODUCTION_TAG}
    container_name: client-app-production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - NODE_ENV=production
    depends_on:
      - instagram-api
      - quant-api
      - logger-api
    networks:
      - back-end

  instagram-api: &instagram-api
    image: ${DOCKER_REGISTRY}crits_and_coffee_api:${INSTAGRAM_API_PRODUCTION_TAG}
    container_name: instagram-api-production
    links:
      - selenium
    depends_on:
      - redis
    networks:
      - back-end
    env_file:
      - ../.envs/.private/.instagram
      - ../.envs/.private/.production/.django
      - ../.envs/.private/.production/.postgres
    command: /start

  quant-api:
    image: ${DOCKER_REGISTRY}crits_and_coffee_api:${QUANT_API_PRODUCTION_TAG}
    container_name: quant-api-production
    depends_on:
      - instagram-api
      - logger-api
    networks:
      - back-end
    env_file:
      - ../.envs/.private/.production/.postgres
      - ../.envs/.private/.production/.flask_quant
      - ../.envs/.private/.quandl
    command: /start

  logger-api:
    image: ${DOCKER_REGISTRY}crits_and_coffee_api:${LOGGER_API_PRODUCTION_TAG}
    container_name: logger-api-production
    volumes:
      - production_logs:/crits-logs/
    networks:
      - back-end
    env_file:
      - ../.envs/.private/.production/.flask_logger
    command: /start

  redis:
    image: redis:3.2
    networks:
      - back-end

  selenium:
    image: selenium/standalone-chrome
    networks:
      - back-end

  celeryworker:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_WORKER_PRODUCTION_TAG}
    container_name: ${CELERY_WORKER_PRODUCTION_TAG}
    command: /start-celeryworker
    networks:
      - back-end

  celerybeat:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_BEAT_PRODUCTION_TAG}
    container_name: ${CELERY_BEAT_PRODUCTION_TAG}
    command: /start-celerybeat
    networks:
      - back-end

  flower:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${FLOWER_PRODUCTION_TAG}
    container_name: ${FLOWER_PRODUCTION_TAG}
    networks:
      - front-end
      - back-end
    ports:
      - "5555:5555"
    command: /start-flower

networks:
  front-end:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
  back-end:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"