version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  front-end-app:
    image: ${DOCKER_REGISTRY}crits_and_coffee_client_app:${DOCKER_TEST_TAG}
    container_name: client-app-test
    build:
      context: ../../CritsAndCoffee.ClientApp/CritsAndCoffeeClientApp
      dockerfile: ../../Docker/compose/production/Dockerfile.ClientApp.Prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - NODE_ENV=production
    depends_on:
      - postgres
      - instagram-api
    networks:
      - front-end
      - selenuim_env


  instagram-api: &instagram-api
    image: ${DOCKER_REGISTRY}crits_and_coffee_api:${INSTAGRAM_API_TEST_TAG}
    container_name: instagram-api-test
    build:
      context: ../../CritsAndCoffee.Instagram.API
      dockerfile: ../Docker/compose/local/Dockerfile.Instagram.API
    volumes:
      - ../../CritsAndCoffee.Instagram.API/functional_tests:/functional_tests
      - ../logs/:/crits-logs/
    links:
      - selenium-hub
    depends_on:
      - postgres
      - mailhog
    networks:
      - selenuim_env
      - front-end
      - back-end
    env_file:
      - ../.envs/.private/.instagram
      - ../.envs/.testing/.django
      - ../.envs/.testing/.postgres
    ports:
      - 8080:8000
    command: /start


  postgres:
    image: ${DOCKER_REGISTRY}crits_and_coffee_postgres:${DOCKER_TEST_TAG}
    container_name: postgres-test
    build:
      context: .
      dockerfile: ./testing/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ../.envs/.testing/.postgres
    networks:
      - selenuim_env
      - back-end

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    networks:
      - selenuim_env
      - back-end

  redis:
    image: redis:3.2
    networks:
      - selenuim_env
      - back-end

  celeryworker:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_WORKER_TEST_TAG}
    container_name: ${CELERY_WORKER_TEST_TAG}
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker
    networks:
      - selenuim_env
      - back-end

  celerybeat:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${CELERY_BEAT_TEST_TAG}
    container_name: ${CELERY_BEAT_TEST_TAG}
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
    networks:
      - selenuim_env
      - back-end

  flower:
    <<: *instagram-api
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${FLOWER_TEST_TAG}
    container_name: ${FLOWER_TEST_TAG}
    ports:
      - "5555:5555"
    command: /start-flower
    networks:
      - selenuim_env
      - back-end

  selenium-hub:
    image: ${DOCKER_REGISTRY}${ACCESSORY_CONTAINER_REPOSITORY}:${SELENIUM_TEST_TAG}
    container_name: selenium-test
    build:
      context: ./testing/selenium
      dockerfile: ./Dockerfile
    privileged: true
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=240000
      - GRID_BROWSER_TIMEOUT=240000
    command: /run_tests
    networks:
      - selenuim_env
      - front-end
      - back-end

  nodechrome2:
    image: selenium/node-chrome-debug
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - 5900:5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenuim_env
      - front-end
      - back-end

  nodefirefox2:
    image: selenium/node-firefox-debug
    privileged: true
    depends_on:
      - selenium-hub
    ports:
      - 5901:5901
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenuim_env
      - front-end
      - back-end

networks:
  selenuim_env:
    driver: bridge
  front-end:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
  back-end:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"